<?php
if (!defined('ABSPATH')) exit;

function aifcms_generate_llms_feed() {
    $output = "# Auto-generated by AI Feed CMS Plugin\n";
    $output .= "# Format: URL | Title | Last Modified\n\n";

    $args = array(
        'post_type' => array('post', 'page'),
        'post_status' => 'publish',
        'posts_per_page' => -1,
        'orderby' => 'modified',
        'order' => 'DESC'
    );

    $posts = get_posts($args);

    foreach ($posts as $post) {
        $url = get_permalink($post->ID);
        $title = get_the_title($post->ID);
        $modified = get_the_modified_date('Y-m-d', $post->ID);

        $output .= esc_url($url) . " | " . sanitize_text_field($title) . " | " . $modified . "\n";
    }

    return $output;
}
